/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import entities.User;
import java.awt.Color;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import models.UserDAO;

/**
 *
 * @author Queen
 */
public class FormLogin extends javax.swing.JFrame {

    static UserDAO _usr;

    /**
     * Creates new form FormLogin
     */
    public FormLogin() {
        initComponents();
        this.setLocationRelativeTo(null);
        _usr = new UserDAO();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        HeaderLogin = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        BodyLogin = new javax.swing.JPanel();
        LabelUsername = new javax.swing.JLabel();
        LoginUsername = new javax.swing.JTextField();
        LabelPassword = new javax.swing.JLabel();
        LoginPassword = new javax.swing.JTextField();
        SubmitLogin = new javax.swing.JButton();
        CreateOne = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        HeaderLogin.setBackground(new java.awt.Color(153, 153, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Sign In");

        javax.swing.GroupLayout HeaderLoginLayout = new javax.swing.GroupLayout(HeaderLogin);
        HeaderLogin.setLayout(HeaderLoginLayout);
        HeaderLoginLayout.setHorizontalGroup(
            HeaderLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, HeaderLoginLayout.createSequentialGroup()
                .addGap(218, 218, 218)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 116, Short.MAX_VALUE)
                .addGap(206, 206, 206))
        );
        HeaderLoginLayout.setVerticalGroup(
            HeaderLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HeaderLoginLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        BodyLogin.setBackground(new java.awt.Color(204, 255, 255));

        LabelUsername.setFont(new java.awt.Font("Tahoma", 2, 16)); // NOI18N
        LabelUsername.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        LabelUsername.setText("Username");

        LoginUsername.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, new java.awt.Color(153, 204, 255), java.awt.Color.white));
        LoginUsername.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        LabelPassword.setFont(new java.awt.Font("Tahoma", 2, 16)); // NOI18N
        LabelPassword.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        LabelPassword.setText("Password");

        LoginPassword.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, new java.awt.Color(153, 204, 255), java.awt.Color.white));
        LoginPassword.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        SubmitLogin.setBackground(new java.awt.Color(102, 153, 255));
        SubmitLogin.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        SubmitLogin.setForeground(new java.awt.Color(255, 255, 255));
        SubmitLogin.setText("Submit");
        SubmitLogin.setAlignmentX(0.5F);
        SubmitLogin.setBorder(null);
        SubmitLogin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        SubmitLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SubmitLoginMouseClicked(evt);
            }
        });

        CreateOne.setBackground(new java.awt.Color(102, 153, 255));
        CreateOne.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        CreateOne.setForeground(new java.awt.Color(102, 153, 255));
        CreateOne.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        CreateOne.setText("No account? Create One!");
        CreateOne.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        CreateOne.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CreateOneMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout BodyLoginLayout = new javax.swing.GroupLayout(BodyLogin);
        BodyLogin.setLayout(BodyLoginLayout);
        BodyLoginLayout.setHorizontalGroup(
            BodyLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BodyLoginLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(BodyLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LoginPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LoginUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(BodyLoginLayout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addGroup(BodyLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(CreateOne)
                            .addComponent(SubmitLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        BodyLoginLayout.setVerticalGroup(
            BodyLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BodyLoginLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(LabelUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LoginUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(LabelPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LoginPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52)
                .addComponent(SubmitLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(CreateOne)
                .addGap(0, 131, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(HeaderLogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(BodyLogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(HeaderLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BodyLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CreateOneMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CreateOneMouseClicked
        if (this.isVisible()) {
            this.setVisible(false);
        }
        new FormRegister().setVisible(true);
    }//GEN-LAST:event_CreateOneMouseClicked

    private void SubmitLoginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SubmitLoginMouseClicked
        if (!this.validateLogin()) {
            User u = new User();
            u.setEmail(LoginUsername.getText());
            u.setPassword(LoginPassword.getText());
            if (_usr.login(u).getEmail()!= null) {
                JOptionPane.showConfirmDialog(null,
                        "Đăng nhập thành công!", "Login", JOptionPane.DEFAULT_OPTION);
                this.setVisible(false);
                new MainJframe(u).setVisible(true);
            } else {
                JOptionPane.showMessageDialog(null, "Tài khoản hoặc mật khẩu không đúng!", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_SubmitLoginMouseClicked
    public boolean validateLogin() {
        StringBuilder errorText = new StringBuilder();

        if (LoginUsername.getText().length() == 0) {
            errorText.append("Vui lòng nhập tên đăng nhập!\n");
            LoginUsername.setBackground(Color.ORANGE);
        }

        if (LoginPassword.getText().length() == 0) {
            errorText.append("Vui lòng nhập mật khẩu!\n");
            LoginPassword.setBackground(Color.ORANGE);
        }

        if (errorText.length() == 0) {
            return false;
        } else {
            JOptionPane.showMessageDialog(null, errorText, "Error", JOptionPane.ERROR_MESSAGE);
            return true;
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BodyLogin;
    private javax.swing.JLabel CreateOne;
    private javax.swing.JPanel HeaderLogin;
    private javax.swing.JLabel LabelPassword;
    private javax.swing.JLabel LabelUsername;
    private javax.swing.JTextField LoginPassword;
    private javax.swing.JTextField LoginUsername;
    private javax.swing.JButton SubmitLogin;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
