/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import entities.LogWork;
import entities.Salary;
import entities.User;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.List;
import java.util.concurrent.atomic.AtomicReference;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import models.LogWorkDao;
import models.SalaryDao;

/**
 *
 * @author Queen
 */
public class JSalary extends javax.swing.JInternalFrame {

    private final User us;
    /**
     * Creates new form JSalary
     */
    public JSalary(User user) {
        this.us = user;
        initComponents();
        loadSalaryByUser();
        jComboBox2.removeAllItems();
        getAllDate();
        
    }

    public void loadSalaryByUser() {
        List<Salary> salaries = new ArrayList<Salary>();
        DefaultTableModel model = (DefaultTableModel) tableSalarySingle.getModel();
        model.setRowCount(0);
        SalaryDao lWDao = new SalaryDao();
        salaries = lWDao.getSalary(us.getId(), false);
        salaries.forEach(sal -> {
            if (sal.getPositionDeletedAt() != null) {
                model.addRow(new Object[]{
                    sal.getId(),
                    String.format("%,.2f", sal.getSalary()) + "VNĐ",
                    sal.getCreatedAt(),
                    "Lương hiện tại",
                    String.format("%,.2f", sal.getSubAmount()) + "VNĐ"
                });
            } else {
                model.addRow(new Object[]{
                    sal.getId(),
                    String.format("%,.2f", sal.getSalary()) + "VNĐ",
                    sal.getCreatedAt(),
                    "Lương cũ",
                    String.format("%,.2f", sal.getSubAmount()) + "VNĐ"
                });
            }
        });
    }

    public void loadAllSalary(int month) {
        List<Salary> salaries = new ArrayList<Salary>();
        DefaultTableModel model = (DefaultTableModel) tableAllSalary.getModel();
        SalaryDao slDao = new SalaryDao();
        AtomicReference<Float> totalSalaryAllUser = new AtomicReference<>();
        model.setRowCount(0);
        salaries = slDao.getSalary(0, true);
        salaries.forEach(sal -> {
            LogWorkDao lwDao = new LogWorkDao();
            Float totalSalaryByMonth = slDao.totalSalaryByInMonth(sal.getUserId(), month);
            if (totalSalaryAllUser.get() == null) {
                totalSalaryAllUser.set(totalSalaryByMonth);
            }else{
                totalSalaryAllUser.set(totalSalaryAllUser.get() + totalSalaryByMonth);
            }
            int totalWorking = lwDao.getByCreatedAt(lwDao.getFirstDayOfMonth(), lwDao.getLastDayOfMonth(), sal.getUserId()).size();
            model.addRow(new Object[]{
                sal.getId(),
                sal.getUsername(),
                sal.getPositionName(),
                String.format("%,.2f", sal.getSalary()) + "VNĐ",
                String.format("%,.2f", sal.getSubAmount()) + "VNĐ",
                totalWorking + "Ngày",
                String.format("%,.2f", totalSalaryByMonth) + "VNĐ"
            });
        });
        jLabel1.setText("Tổng tiền lương của tháng: " + String.format("%,.2f", totalSalaryAllUser.get()) + "VNĐ");
    }
    
    public void getAllDate(){
        Date today = new Date();
        Calendar calendar = Calendar.getInstance();
        calendar.setTime(today);
        int currentMonth = calendar.get(Calendar.MONTH);
        for (int i = 1; i <= currentMonth + 1; i++) {
            jComboBox2.addItem("Tháng " + i);
            if (i == currentMonth + 1) {
                jComboBox2.setSelectedIndex(i - 1);
            }
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableSalarySingle = new javax.swing.JTable();
        jButton3 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableAllSalary = new javax.swing.JTable();
        jComboBox2 = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();

        jButton2.setText("jButton2");

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane5.setViewportView(jTable3);

        tableSalarySingle.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Tiền lương", "Ngày bắt đầu", "Trạng thái", "Phụ cấp"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableSalarySingle.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jScrollPane2.setViewportView(tableSalarySingle);

        jButton3.setText("Lương tháng này");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(0, 407, Short.MAX_VALUE)
                .addComponent(jButton3))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 502, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addComponent(jButton3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 351, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Bản thân", jPanel2);

        tableAllSalary.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Họ tên", "Chức vụ", "Mức lương", "Hỗ trợ", "Số ngày công", "Lương tháng"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, true, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tableAllSalary);

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });

        jLabel1.setText("Tổng tiền lương của tháng:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 522, Short.MAX_VALUE)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 314, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Tất cả", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        SalaryDao slDao = new SalaryDao();
        Float totalSalary = slDao.totalSalaryByInMonth(us.getId(), 5);
        JOptionPane.showMessageDialog(jPanel2, "Tổng tiền lương tháng này: " + String.format("%,.2f", totalSalary) + "VNĐ");
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        String month = String.valueOf(jComboBox2.getSelectedItem());
        if (month.length() > 5) {
            month = month.substring(5).trim();
            int conMonth = Integer.parseInt(month);
            loadAllSalary(conMonth);
        }
    }//GEN-LAST:event_jComboBox2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable3;
    private javax.swing.JTable tableAllSalary;
    private javax.swing.JTable tableSalarySingle;
    // End of variables declaration//GEN-END:variables
}
