/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import entities.User;
import java.awt.BorderLayout;
import java.awt.Insets;
import java.beans.PropertyVetoException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JInternalFrame;
import javax.swing.JLabel;
import javax.swing.JPanel;

/**
 *
 * @author Administrator
 */
public class MainJframe extends javax.swing.JFrame {

    private User us;

    /**
     * Creates new form MainJframe
     */
    public MainJframe(User us) {
        initComponents();
        this.setLocationRelativeTo(null);
        this.us = us;
        this.username.setText(us.getLast_name() + " " + us.getFirst_name());
//        JDashboard jf = new JDashboard();
//        jf.setVisible(true);
//        Main.add(jf);
//        try {
//            jf.setSelected(true);
//        } catch (PropertyVetoException ex) {
//            Logger.getLogger(MainJframe.class.getName()).log(Level.SEVERE, null, ex);
//        }
//        setContentPane(Main);
//        Main.getRootPane().add(this)
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        HeaderMain = new javax.swing.JPanel();
        username = new javax.swing.JLabel();
        Logout = new javax.swing.JLabel();
        MenuBar = new javax.swing.JPanel();
        BtnProfile = new javax.swing.JButton();
        BtnDepartment = new javax.swing.JButton();
        BtnHR = new javax.swing.JButton();
        BtnLogWork = new javax.swing.JButton();
        BtnSalary = new javax.swing.JButton();
        BtnExtend = new javax.swing.JButton();
        Main = new javax.swing.JTabbedPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        HeaderMain.setBackground(new java.awt.Color(153, 153, 153));

        username.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        username.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8-customer-24.png"))); // NOI18N

        Logout.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Logout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8-export-24.png"))); // NOI18N
        Logout.setText("Log out");
        Logout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LogoutMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout HeaderMainLayout = new javax.swing.GroupLayout(HeaderMain);
        HeaderMain.setLayout(HeaderMainLayout);
        HeaderMainLayout.setHorizontalGroup(
            HeaderMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HeaderMainLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(username)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Logout)
                .addGap(18, 18, 18))
        );
        HeaderMainLayout.setVerticalGroup(
            HeaderMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HeaderMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(username, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Logout, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        MenuBar.setBackground(new java.awt.Color(102, 255, 255));

        BtnProfile.setBackground(new java.awt.Color(51, 153, 255));
        BtnProfile.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        BtnProfile.setForeground(new java.awt.Color(255, 255, 255));
        BtnProfile.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8-admin-settings-male-24.png"))); // NOI18N
        BtnProfile.setText("Thông tin tài khoản");
        BtnProfile.setBorder(null);
        BtnProfile.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtnProfile.setFocusable(false);
        BtnProfile.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        BtnProfile.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnProfileMouseClicked(evt);
            }
        });
        BtnProfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnProfileActionPerformed(evt);
            }
        });

        BtnDepartment.setBackground(new java.awt.Color(51, 153, 255));
        BtnDepartment.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        BtnDepartment.setForeground(new java.awt.Color(255, 255, 255));
        BtnDepartment.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8-department-24.png"))); // NOI18N
        BtnDepartment.setText("Phòng ban và vị trí");
        BtnDepartment.setBorder(null);
        BtnDepartment.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtnDepartment.setFocusable(false);
        BtnDepartment.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        BtnDepartment.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnDepartmentMouseClicked(evt);
            }
        });
        BtnDepartment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnDepartmentActionPerformed(evt);
            }
        });

        BtnHR.setBackground(new java.awt.Color(51, 153, 255));
        BtnHR.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        BtnHR.setForeground(new java.awt.Color(255, 255, 255));
        BtnHR.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8-user-account-24.png"))); // NOI18N
        BtnHR.setText("Danh sách nhân sự");
        BtnHR.setBorder(null);
        BtnHR.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtnHR.setFocusable(false);
        BtnHR.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        BtnHR.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnHRMouseClicked(evt);
            }
        });
        BtnHR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnHRActionPerformed(evt);
            }
        });

        BtnLogWork.setBackground(new java.awt.Color(51, 153, 255));
        BtnLogWork.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        BtnLogWork.setForeground(new java.awt.Color(255, 255, 255));
        BtnLogWork.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8-log-24.png"))); // NOI18N
        BtnLogWork.setText("Chấm công");
        BtnLogWork.setBorder(null);
        BtnLogWork.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtnLogWork.setFocusable(false);
        BtnLogWork.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        BtnLogWork.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnLogWorkMouseClicked(evt);
            }
        });
        BtnLogWork.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnLogWorkActionPerformed(evt);
            }
        });

        BtnSalary.setBackground(new java.awt.Color(51, 153, 255));
        BtnSalary.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        BtnSalary.setForeground(new java.awt.Color(255, 255, 255));
        BtnSalary.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8-salary-male-24.png"))); // NOI18N
        BtnSalary.setText("Thông kê tiền lương");
        BtnSalary.setBorder(null);
        BtnSalary.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtnSalary.setFocusable(false);
        BtnSalary.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        BtnSalary.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnSalaryMouseClicked(evt);
            }
        });
        BtnSalary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSalaryActionPerformed(evt);
            }
        });

        BtnExtend.setBackground(new java.awt.Color(51, 153, 255));
        BtnExtend.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        BtnExtend.setForeground(new java.awt.Color(255, 255, 255));
        BtnExtend.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8-zoom-out-24.png"))); // NOI18N
        BtnExtend.setText("Mở rộng");
        BtnExtend.setBorder(null);
        BtnExtend.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtnExtend.setFocusable(false);
        BtnExtend.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnExtendMouseClicked(evt);
            }
        });
        BtnExtend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnExtendActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout MenuBarLayout = new javax.swing.GroupLayout(MenuBar);
        MenuBar.setLayout(MenuBarLayout);
        MenuBarLayout.setHorizontalGroup(
            MenuBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BtnProfile, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(BtnDepartment, javax.swing.GroupLayout.DEFAULT_SIZE, 182, Short.MAX_VALUE)
            .addComponent(BtnHR, javax.swing.GroupLayout.DEFAULT_SIZE, 182, Short.MAX_VALUE)
            .addComponent(BtnLogWork, javax.swing.GroupLayout.DEFAULT_SIZE, 182, Short.MAX_VALUE)
            .addComponent(BtnSalary, javax.swing.GroupLayout.DEFAULT_SIZE, 182, Short.MAX_VALUE)
            .addComponent(BtnExtend, javax.swing.GroupLayout.DEFAULT_SIZE, 182, Short.MAX_VALUE)
        );
        MenuBarLayout.setVerticalGroup(
            MenuBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuBarLayout.createSequentialGroup()
                .addComponent(BtnProfile, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BtnDepartment, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BtnHR, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BtnLogWork, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BtnSalary, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 171, Short.MAX_VALUE)
                .addComponent(BtnExtend, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(HeaderMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(MenuBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Main, javax.swing.GroupLayout.DEFAULT_SIZE, 997, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(HeaderMain, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(MenuBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Main)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogoutMouseClicked
        this.setVisible(false);
        new FormLogin().setVisible(true);
    }//GEN-LAST:event_LogoutMouseClicked

    private void BtnProfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnProfileActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnProfileActionPerformed

    private void BtnDepartmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnDepartmentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnDepartmentActionPerformed

    private void BtnHRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnHRActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnHRActionPerformed

    private void BtnLogWorkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnLogWorkActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnLogWorkActionPerformed

    private void BtnSalaryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSalaryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnSalaryActionPerformed

    private void BtnExtendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnExtendActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnExtendActionPerformed

    private void BtnProfileMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnProfileMouseClicked
        int i = checkExistTab("Profile");
        if (i < 0) {
            JPanel tab1 = new JPanel(new BorderLayout());
            JInternalFrame fd = new JProfile();
            tab1.add(fd.getContentPane());
            Main.addTab("Profile", tab1);
        }else{
            Main.setSelectedIndex(i);
        }
    }//GEN-LAST:event_BtnProfileMouseClicked

    public int checkExistTab(String tabName) {
        int totalTab = Main.getTabCount();
        int check = -1;
        for (int i = 0; i < totalTab; i++) {
            if (Main.getTitleAt(i).equals(tabName)) {
                check = i;
            }
        }
        return check;
    }

    private void BtnDepartmentMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnDepartmentMouseClicked
        int i = checkExistTab("Department");
        if (i < 0) {
            JPanel tab2 = new JPanel(new BorderLayout());
            JInternalFrame fd = new JDepartment();
            tab2.add(fd.getContentPane());
            Main.addTab("Department", tab2);
        }else{
            Main.setSelectedIndex(i);
        }
    }//GEN-LAST:event_BtnDepartmentMouseClicked

    private void BtnHRMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnHRMouseClicked
        int i = checkExistTab("Humam Resource");
        if (i < 0) {
            JPanel tab3 = new JPanel(new BorderLayout());
            JInternalFrame fd = new JHumanResource();
            tab3.add(fd.getContentPane());
            Main.addTab("Humam Resource", tab3);
        }else{
            Main.setSelectedIndex(i);
        }
    }//GEN-LAST:event_BtnHRMouseClicked

    private void BtnLogWorkMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnLogWorkMouseClicked
        int i = checkExistTab("Log Work");
        if (i < 0) {
            JPanel tab4 = new JPanel(new BorderLayout());
            JInternalFrame fd = new JLogWork(this.us);
            tab4.add(fd.getContentPane());
            Main.addTab("Log Work", tab4);
        }else{
            Main.setSelectedIndex(i);
        }
    }//GEN-LAST:event_BtnLogWorkMouseClicked

    private void BtnSalaryMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnSalaryMouseClicked
        int i = checkExistTab("Salary");
        if (i < 0) {
            JPanel tab5 = new JPanel(new BorderLayout());
            JInternalFrame fd = new JSalary(this.us);
            tab5.add(fd.getContentPane());
            Main.addTab("Salary", tab5);
        }else{
            Main.setSelectedIndex(i);
        }
    }//GEN-LAST:event_BtnSalaryMouseClicked

    private void BtnExtendMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnExtendMouseClicked
        int i = checkExistTab("Extends");
        if (i < 0) {
            JPanel tab6 = new JPanel(new BorderLayout());
            JInternalFrame fd = new JExtend();
            tab6.add(fd.getContentPane());
            Main.addTab("Extends", tab6);
        }else{
            Main.setSelectedIndex(i);
        }
    }//GEN-LAST:event_BtnExtendMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[], User us) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainJframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainJframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainJframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainJframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainJframe(us).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnDepartment;
    private javax.swing.JButton BtnExtend;
    private javax.swing.JButton BtnHR;
    private javax.swing.JButton BtnLogWork;
    private javax.swing.JButton BtnProfile;
    private javax.swing.JButton BtnSalary;
    private javax.swing.JPanel HeaderMain;
    private javax.swing.JLabel Logout;
    private javax.swing.JTabbedPane Main;
    private javax.swing.JPanel MenuBar;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JLabel username;
    // End of variables declaration//GEN-END:variables
}
